{% set version = "1.10.0" %}

package:
  name: event-model
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/event-model
  git_rev: v{{ version }}

build:
  number: 9 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
    - pytest
    - pytest-runner
  run:
    - jsonschema >=3.0.0
    - numpy
    - python

test:
  requires:
    - pytest
  imports:
    - event_model
  commands:
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/NSLS-II/event_model
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - CJ-Wright
    - danielballan
    - ericdill
    - licode
    - mrakitin
    - tacaswell
