{% set name = "event-model" %}
{% set version = "1.11.2" %}
{% set sha256 = "4f09bf0f20ca0ffe390f781a9a72dee38166f97155ca48a148cc739f2bcd29e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jsonschema
    - numpy

test:
  requires:
    - pytest
  imports:
    - event_model
  commands:
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/bluesky/event-model
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Data model for event-based data collection and analysis
