{% set version = "1.10.0" %}

package:
  name: event-model
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/event-model
  git_rev: v{{ version }}

build:
  number: 7
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py<36]

requirements:
  host:
    - python
    - setuptools
  run:
    - jsonschema >=3.0.0
    - numpy
    - python

test:
  imports:
    - event_model

about:
  home: https://github.com/NSLS-II/event_model
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - CJ-Wright
    - danielballan
    - ericdill
    - licode
    - mrakitin
    - tacaswell
