{% set name = "event-model" %}
{% set version = "1.17.1" %}
{% set sha256 = "6a21de06b4f63ac4882bfa70f6ef39ac987f1cc537489944209c59b5202a87b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jsonschema
    - numpy

test:
  requires:
    - pytest
  imports:
    - event_model
  commands:
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/bluesky/event-model
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Data model for event-based data collection and analysis
